CREATE TABLE FLIGHT_SCHEDULE (
 FLIGhT_SCH_ID INTEGER PRIMARY KEY auto_increment,
 FLIGHT_N0 INTEGER,
 FLIGHT_DATE DATE,
 FLIGHT_TIME TIME,
 CITY_FROM VARCHAR(50),
 CITY_TO VARCHAR(50),
 AIRCRAFT_NO INTEGER,
 FOREIGN KEY (FLIGHT_N0) REFERENCES AIRCRAFT(AIRCRAFT_NO)
 
 );
 CREATE TABLE AIRCRAFT(
 AIRCRAFT_NO INTEGER auto_increment ,
 AIRCRAFT_NAME VARCHAR(50),
 AIRCRAFT_TYPE VARCHAR(50),
 TOTAL_SEATS VARCHAR(50),
 
 PRIMARY KEY(AIRCRAFT_NO)
 );
 CREATE TABLE PASSENGER(
 PNR_NO INTEGER primary key auto_increment ,
 PNR_NAME VARCHAR(50),
 BIRTH_DATE DATE,
 ID_PROOF VARCHAR(50),
 PNR_MOBILE VARCHAR(10),
 PNR_EMAIL VARCHAR(40)
  );
CREATE TABLE BOOKING(
 BOOKING_ID INTEGER primary key auto_increment ,
 FLIGhT_SCH_ID INTEGER, 
 SEAT_NO INTEGER,

 FOREIGN KEY (FLIGHT_SCH_ID) REFERENCES FLIGHT_SCHEDULE(FLIGhT_SCH_ID)
 );
 

 